# Generated by Django 3.2.23 on 2024-02-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('accessories', 'Accessories'), ('bikes', 'Bikes'), ('components', 'Components'), ('clothing', 'Clothing'), ('health and fitness', 'Health and Fitness'), ('tools and workshop', 'Tools and Workshop')], default='Accessories', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
